services:

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    restart: unless-stopped
    networks:
      - calculator-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      SERVER_PORT: 9000
      JVM_OPTS: "-Xms32M -Xmx64M"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - calculator-network


  calculator:
    build:
      context: ./calculator
    container_name: calculator
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - calculator-network
    volumes:
      - ./logs/calculator:/app/logs
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOGGING_LEVEL_ORG_APACHE_KAFKA: WARN
      LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS_PRODUCER: WARN
      LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS_CONSUMER: WARN

  rest:
    build:
      context: ./rest
    container_name: rest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - calculator-network
    volumes:
      - ./logs/rest:/app/logs
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOGGING_LEVEL_ORG_APACHE_KAFKA: WARN
      LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS_PRODUCER: WARN
      LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS_CONSUMER: WARN

networks:
  calculator-network:
    driver: bridge
